### ISSUE TITLE
SQLBlock Source code require.

### ISSUE THREAD

**Issue by DuckYellowPP** [BUseclab/saphire#2]
Dear Dr.​Rasoul,

I read your paper "You shall not pass: Mitigating SQL Injection Attacks on Legacy Web Applications".

I'm very interested in your work, which is similar to my idea of working on SQL defense, when I was about to read the source code, I found the link https://github.com/BUseclab/SQLBlock has expired, can you send me the updated link?

**Comment by reddevil-j** [comment]
The Github repo is now available through with the link you have now.
